# Generated by Django 6.1 on 2026-09-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citta',
            fields=[
                ('geonameid', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('paese', models.CharField(max_length=2)),
                ('popolazione', models.IntegerField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('chiave', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'città',
            },
        ),
        migrations.CreateModel(
            name='Comune',
            fields=[
                ('codice', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('sigla_provincia', models.CharField(max_length=2)),
                ('regione', models.CharField(max_length=50)),
                ('alt_min', models.IntegerField(null=True)),
                ('alt_max', models.IntegerField(null=True)),
                ('popolazione', models.IntegerField(default=0)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('chiave', models.CharField(db_index=True, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'comuni',
            },
        ),
    ]
