"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path

from django.core.management.utils import get_random_secret_key

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

# Senza DJANGO_SECRET_KEY (sviluppo, job di export) una chiave casuale per processo: niente chiave
# fissa nel codice. Il web in produzione la riceve dall'env.
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY') or get_random_secret_key()

ALLOWED_HOSTS = [h for h in os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',') if h]

CSRF_TRUSTED_ORIGINS = [o for o in os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',') if o]

# Dietro Cloud Run / Cloudflare che terminano l'HTTPS e inoltrano a gunicorn in HTTP: senza
# questi Django crede di essere in http:// (redirect/CSRF sbagliati). In locale sono innocui.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True


# Application definition

# Niente admin/auth/sessioni: il sito è pubblico, in sola lettura, senza utenti.
INSTALLED_APPS = [
    'django.contrib.contenttypes',
    'django.contrib.staticfiles',
    'luoghi',
    'places',
    'copernicus',
    'pagine',
    'django_htmx',
]

MIDDLEWARE = [
    # risposte compresse (Cloud Run non comprime): JSON della griglia e pagine ~70% in meno.
    # Niente rischio BREACH: il sito non ha form, sessioni né segreti nelle pagine.
    'django.middleware.gzip.GZipMiddleware',
    'django.middleware.security.SecurityMiddleware',
    # lingua dal prefisso dell'URL (/it/…); senza prefisso inglese
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_htmx.middleware.HtmxMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.template.context_processors.i18n',
                'config.lingue.lingue',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Unico DB: SQLite in sola lettura con comuni e città, costruito in fase di build dell'immagine
# (`migrate` + `luoghi_load`). I dati CAMS non stanno qui ma nei Parquet (CAMS_STORAGE).
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.environ.get('LUOGHI_DB', str(BASE_DIR / 'luoghi.sqlite3')),
    }
}


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

# Inglese di default (URL senza prefisso), italiano sotto /it/. Testi sorgente in inglese,
# traduzioni in locale/<lingua>/LC_MESSAGES/django.po (i .mo si compilano, non si versionano).
LANGUAGE_CODE = 'en'

LANGUAGES = [
    ('en', 'English'),
    ('it', 'Italiano'),
]

LOCALE_PATHS = [BASE_DIR / 'locale']

TIME_ZONE = 'Europe/Rome'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'


# copernicus: dati qualità dell'aria da CAMS (Copernicus Atmosphere Data Store)

CDS_API_URL = os.environ.get('CDS_API_URL', 'https://ads.atmosphere.copernicus.eu/api')
CDS_API_KEY = os.environ.get('CDS_API_KEY')

# Dove il job pubblica i Parquet giornalieri e da dove il web li legge: `gs://bucket/prefisso`
# (bucket pubblico in lettura, il web lo legge via HTTPS) oppure una cartella locale in sviluppo.
CAMS_STORAGE = os.environ.get('CAMS_STORAGE', str(BASE_DIR / 'data' / 'cams'))

# CARTO ora richiede una API key anche per i basemap tile gratuiti (dark_all/light_all su
# basemaps.cartocdn.com) — senza non vengono più serviti. Chiave gratuita da carto.com.
CARTO_API_KEY = os.environ.get('CARTO_API_KEY')

# Stile basemap CARTO: 'dark_all' o 'light_all' (altri disponibili: light_nolabels,
# dark_nolabels, light_only_labels, dark_only_labels).
CARTO_BASEMAP_STYLE = os.environ.get('CARTO_BASEMAP_STYLE', 'dark_all')

# Centro proposto quando l'URL non ne indica uno. Default: Mezzolombardo (TN)
COPERNICUS_LATITUDE = float(os.environ.get('COPERNICUS_LATITUDE', '46.215022'))
COPERNICUS_LONGITUDE = float(os.environ.get('COPERNICUS_LONGITUDE', '11.092251'))

# Inquinanti esportati dal job e mostrati in mappa (sottoinsieme di pm2p5, pm10, no2, o3, so2)
COPERNICUS_POLLUTANTS = [
    p.strip() for p in os.environ.get('COPERNICUS_POLLUTANTS', 'pm2p5,pm10,no2,o3,so2').split(',') if p.strip()
]

# Giorni di corse annunciati nell'indice (la cancellazione vera la fa la lifecycle rule del bucket)
COPERNICUS_RETENTION_DAYS = int(os.environ.get('COPERNICUS_RETENTION_DAYS', '21'))

# Soglie di allarme qualità dell'aria (µg/m³)
# Valori di default = soglie UE (per PM2,5/PM10 i limiti giornalieri dal 2030); regolabili via env senza
# toccare codice (es. se le normative cambiano o si vuole una soglia più conservativa).
COPERNICUS_SOGLIE_ALLARME = {
    'pm2p5': float(os.environ.get('COPERNICUS_SOGLIA_PM2P5', '25.0')),  # limite giornaliero UE dal 2030 (Dir. 2024/2881)
    'pm10': float(os.environ.get('COPERNICUS_SOGLIA_PM10', '45.0')),    # limite giornaliero UE dal 2030 (Dir. 2024/2881)
    'no2': float(os.environ.get('COPERNICUS_SOGLIA_NO2', '200.0')),     # soglia oraria UE
    'o3': float(os.environ.get('COPERNICUS_SOGLIA_O3', '180.0')),       # soglia oraria UE
    'so2': float(os.environ.get('COPERNICUS_SOGLIA_SO2', '350.0')),     # soglia oraria UE
}
